### ISSUE TITLE
Subscrptions not adding to SMS flow

### ISSUE THREAD

**Issue by livemylife** [chadsmith/OpenVBX-Plugin-Subscriptions#13]
Hey Chad Subscriptions working fine on Call Flow but nothing on SMS flow.  

i originally tried with Match and Subscription where the flow seemed to work fine as i got the response but nothing entered into the list. 

i also tried to just do Subscription where again i get the next action which was a SMS but the number was not entered into a list. 

I also added the Subscription to the Call flow and it adds the number just fine when i call into the twilio number. 

OpenVBX version - v1.2.9 r75
host - Dreamhost
site = txtdepot.com/vbx
list name - newlist
sender area code - 403 - Calgary, AB Canada

I would appreciate an idea of where to go from here. 

Dwight 

twitter.com/dwightgelowitz

**Comment by smellyspice** [comment]
I'm getting the same thing. Oddly, it seemed to have worked the very first time I tried it, but after removing and retrying - nothing is getting added to the list, even though the Next Action is being executed. I even tried dropping the tables and starting fresh (since the scripts appear to call db.sql to create if exists) and no joy. 

I'm running OpenVBX • v1.2.10 r76 on an internal VM running Tunrkey Linux - LAMP.

Thanks,

-Rob

**Comment by gothamtommy** [comment]
Same issue. All TwiML outputs look like this:

<?xml version="1.0" encoding="UTF-8"?>
<Response/>

**Comment by BillyParadise** [comment]
I spoke with Chad - update will be made shortly!

**Comment by chadsmith** [comment]
It wasn't adding them because Twilio no longer sends Direction on incoming SMSs. I just pushed an update to fix that.
